const DATE_CHANGE = "DATE_CHANGE";
const INPUT_CHANGE = "DATE_CHANGE";
const FORM_VALIDATION = "FORM_VALIDATION";
const IS_CONFIRMATION = "IS_CONFIRMATION";
const SUBMIT_LOADING = "SUBMIT_LOADING";

export default {
  INPUT_CHANGE,
  DATE_CHANGE,
  FORM_VALIDATION,
  IS_CONFIRMATION,
  SUBMIT_LOADING,
};
